theme: jekyll-theme-cayman
kramdown:
  math_engine: mathjax
show_downloads: true
github:
  paper_url: https://arxiv.org/abs/2505.13740
  code_url: https://github.com/rainorangelemon/complift
twitter:
  card: "summary_large_image"     # This sets the card type site-wide